name: 'Setup Gradle with caching'
description: 'Sets up Gradle with dependency caching'
inputs:
  cache-read-only:
    description: 'Whether to use read-only cache'
    required: false
    default: 'false'
  gradle-home-cache-cleanup:
    description: 'Whether to cleanup gradle home cache'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Cache Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/gradle.lockfile', '**/buildscript-gradle.lockfile') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v5
      with:
        cache-read-only: ${{ inputs.cache-read-only }}
        gradle-home-cache-cleanup: ${{ inputs.gradle-home-cache-cleanup }}
